version: '3.6'

services:
  jupyter:
     build:
       context: .
       dockerfile: ./binder/Dockerfile
     ports:
       - ${PORT}:8888
     volumes:
       - ./work:/home/${NB_USER}/work

     # there is no need to specify the command. This is inherited from the Dockerfile
